server:
  port: 8080

spring:
  datasource:
    url:  jdbc:mysql://${dbHost}:${dbPort}/${dbName}?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${dbUsername}
    password: ${dbPassword}
  redis:
    host: ${redisHost}
    port: ${redisPort}
  session:
    store-type: redis
    redis:
      namespace: moeconn:spring:session
mybatis-plus:
  mapper-locations: classpath*:dao/*.xml
logging:
  level:
    root: WARN
mail:
  qq:
    secret-key: gxpndzfymhcibdib
    smtp-host: smtp.qq.com
    send-mail: 740712697@qq.com
    auth: "true"