server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${dbHost}:${dbPort}/${dbName}?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${dbUsername}
    password: ${dbPassword}
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: ${redisHost}
    port: ${redisPort}
    password: ${redisPassword}
  session:
    store-type: redis
    redis:
      namespace: moeconn:spring:session
    timeout: 3600000
  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    root: INFO

mail:
  qq:
    secret-key: gxpndzfymhcibdib
    smtp-host: smtp.qq.com
    send-mail: ${sendMail}
    auth: "true"
